# Copyright (c) RedTiger
# See the file 'LICENSE' for copying permission

from Config.Util import *
from Config.Config import *

try:
    import winreg, os, sys, re, time, subprocess, threading
    import ctypes
except Exception as e:
    ErrorModule(e)

try:
    import customtkinter as ctk
    from tkinter import messagebox
except Exception:
    try:
        import subprocess as _subp
        _subp.run([sys.executable, "-m", "pip", "install", "--quiet",
                   "--disable-pip-version-check", "customtkinter"],
                  stdout=_subp.DEVNULL, stderr=_subp.DEVNULL, timeout=120)
    except Exception: pass
    import customtkinter as ctk
    from tkinter import messagebox

Title("Virus Remover")

# ══════════════════════════════════════════════════════════════════════════════
#  DETECTION HELPERS
# ══════════════════════════════════════════════════════════════════════════════

_SUSPICIOUS_DIRS = [
    os.environ.get("TEMP", ""),
    os.environ.get("TMP", ""),
    os.environ.get("APPDATA", ""),
    os.path.join(os.environ.get("LOCALAPPDATA", ""), "Temp"),
    os.path.join(os.environ.get("USERPROFILE", ""), "AppData", "Roaming"),
    r"C:\Users\Public",
    r"C:\Windows\Temp",
]
_SUSPICIOUS_DIRS = [d.lower() for d in _SUSPICIOUS_DIRS if d]

_VOWELS = set("aeiouAEIOU")
_SYSTEM_NAMES = {
    "svchost.exe","lsass.exe","csrss.exe","wininit.exe","winlogon.exe",
    "services.exe","smss.exe","explorer.exe","taskhost.exe","taskhostw.exe",
    "dwm.exe","conhost.exe","spoolsv.exe","SearchIndexer.exe",
    "python.exe","pythonw.exe","cmd.exe","powershell.exe",
}

_MALWARE_KW = [
    "webhook","discord","telegram","keylog","stealer","rat","trojan",
    "payload","inject","grab","spy","hook","dump","token",
]

def _is_suspicious_name(name: str) -> str | None:
    base = os.path.splitext(name)[0].lower()
    if len(base) < 4:
        return "very short name"
    vowel_ratio = sum(1 for c in base if c in _VOWELS) / max(len(base), 1)
    if vowel_ratio < 0.10 and len(base) >= 5:
        return "no vowels (random-looking)"
    typos = {
        "svch0st","svchost32","svchost64","lsasss","csrss32",
        "explore","exploler","wscript32","wscript64","rundl132",
        "taskmgr32","regedt32","noteapd","chrom","googl",
    }
    if base in typos:
        return "typosquatting system name"
    if re.match(r'^[a-z]{1,3}[0-9]+[a-z]{0,3}$', base):
        return "alphanumeric random pattern"
    return None

def _is_suspicious_path(path: str) -> str | None:
    pl = path.lower()
    for d in _SUSPICIOUS_DIRS:
        if d and pl.startswith(d):
            return f"in suspicious dir: {os.path.dirname(path)}"
    if pl.endswith(".pyw") or pl.endswith(".py"):
        return "Python script as startup"
    for kw in _MALWARE_KW:
        if kw in pl:
            return f"keyword '{kw}' in path"
    return None

def _score(name: str, path: str) -> list[str]:
    reasons = []
    r = _is_suspicious_name(os.path.basename(name))
    if r: reasons.append(r)
    r = _is_suspicious_path(path)
    if r: reasons.append(r)
    return reasons

# ══════════════════════════════════════════════════════════════════════════════
#  BINARY SIGNATURE SCANNER  — detects builds generated by this builder
# ══════════════════════════════════════════════════════════════════════════════

_BUILDER_SIGS = [
    b'v4r_c2_wh',
    b'v4r_c2sub',
    b'_v4r_post',
    b'ClaudeCodeUpdater',
    b'WindowsUpdateService',
    b'discord.com/api/webhooks',
    b'discord.com\\api\\webhooks',
    b'__WEBHOOK__',
]
_MAX_BIN_SCAN = 4 * 1024 * 1024  # 4 MB cap

def _scan_binary(path: str) -> str | None:
    """Return reason string if the binary matches builder signatures, else None."""
    try:
        size = os.path.getsize(path)
        if size > 80 * 1024 * 1024:
            return None
        with open(path, 'rb') as f:
            data = f.read(min(size, _MAX_BIN_SCAN))
        for sig in _BUILDER_SIGS:
            if sig in data:
                return f'builder signature: {sig.decode("utf-8", "ignore")}'
    except Exception:
        pass
    return None

# ══════════════════════════════════════════════════════════════════════════════
#  REGISTRY SCANNER
# ══════════════════════════════════════════════════════════════════════════════

_RUN_KEYS = [
    (winreg.HKEY_CURRENT_USER,  r"Software\Microsoft\Windows\CurrentVersion\Run"),
    (winreg.HKEY_CURRENT_USER,  r"Software\Microsoft\Windows\CurrentVersion\RunOnce"),
    (winreg.HKEY_LOCAL_MACHINE, r"Software\Microsoft\Windows\CurrentVersion\Run"),
    (winreg.HKEY_LOCAL_MACHINE, r"Software\Microsoft\Windows\CurrentVersion\RunOnce"),
    (winreg.HKEY_LOCAL_MACHINE, r"Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Run"),
    (winreg.HKEY_CURRENT_USER,  r"Software\Microsoft\Windows NT\CurrentVersion\Windows"),
]

_HIVE_NAMES = {
    winreg.HKEY_CURRENT_USER:  "HKCU",
    winreg.HKEY_LOCAL_MACHINE: "HKLM",
}

def scan_registry() -> list[dict]:
    results = []
    for hive, key_path in _RUN_KEYS:
        try:
            hk = winreg.OpenKey(hive, key_path, 0, winreg.KEY_READ)
            i = 0
            while True:
                try:
                    name, data, _ = winreg.EnumValue(hk, i)
                    if not isinstance(data, str):
                        data = str(data)
                    path = data.strip().strip('"').split('"')[0].split(' ')[0] if '"' not in data else data.split('"')[1]
                    reasons = _score(name, path)
                    # Deep-scan the registered executable for builder signatures
                    if path and os.path.isfile(path) and path.lower().endswith('.exe'):
                        sig = _scan_binary(path)
                        if sig and sig not in reasons:
                            reasons.append(sig)
                    results.append({
                        "hive":    _HIVE_NAMES.get(hive, "?"),
                        "key":     key_path,
                        "name":    name,
                        "path":    path,
                        "raw":     data,
                        "reasons": reasons,
                    })
                    i += 1
                except OSError:
                    break
            winreg.CloseKey(hk)
        except (OSError, PermissionError):
            pass
    return results

def _delete_registry_value(hive_str: str, key_path: str, name: str) -> bool:
    hive_map = {"HKCU": winreg.HKEY_CURRENT_USER, "HKLM": winreg.HKEY_LOCAL_MACHINE}
    hive = hive_map.get(hive_str)
    if not hive:
        return False
    try:
        hk = winreg.OpenKey(hive, key_path, 0, winreg.KEY_SET_VALUE)
        winreg.DeleteValue(hk, name)
        winreg.CloseKey(hk)
        return True
    except Exception:
        return False

# ══════════════════════════════════════════════════════════════════════════════
#  PROCESS SCANNER
# ══════════════════════════════════════════════════════════════════════════════

def scan_processes() -> list[dict]:
    results = []
    try:
        import psutil
        for proc in psutil.process_iter(['pid', 'name', 'exe']):
            try:
                name = proc.info['name'] or ""
                path = proc.info['exe'] or name
                pid  = str(proc.info['pid'])
                reasons = _score(name, path)
                results.append({"pid": pid, "name": name, "path": path, "reasons": reasons})
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                pass
        return results
    except ImportError:
        pass

    try:
        raw = subprocess.check_output(
            ["tasklist", "/FO", "CSV", "/NH"],
            stderr=subprocess.DEVNULL, creationflags=subprocess.CREATE_NO_WINDOW,
            timeout=12
        ).decode("utf-8", "ignore")
        for line in raw.splitlines():
            line = line.strip()
            if not line:
                continue
            parts = [p.strip('"') for p in line.split('","')]
            if len(parts) < 2:
                continue
            name = parts[0]; pid = parts[1]
            if not name or name == "Image Name":
                continue
            reasons = _score(name, name)
            results.append({"pid": pid, "name": name, "path": name, "reasons": reasons})
        return results
    except Exception:
        pass

    try:
        raw = subprocess.check_output(
            ["wmic", "process", "get", "ExecutablePath,Name,ProcessId", "/format:csv"],
            stderr=subprocess.DEVNULL, creationflags=subprocess.CREATE_NO_WINDOW,
            timeout=15
        ).decode("utf-8-sig", "ignore")
        for line in raw.splitlines():
            line = line.strip()
            if not line or "," not in line:
                continue
            parts = [p.strip() for p in line.split(",")]
            if len(parts) < 4 or parts[2].lower() in ("name", ""):
                continue
            _, path, name, pid = parts[0], parts[1], parts[2], parts[3]
            if not name:
                continue
            reasons = _score(name, path or name)
            results.append({"pid": pid, "name": name, "path": path or name, "reasons": reasons})
    except Exception:
        pass

    return results

def kill_process(pid: str, name: str) -> bool:
    try:
        subprocess.run(
            ["taskkill", "/F", "/PID", pid],
            capture_output=True, creationflags=subprocess.CREATE_NO_WINDOW
        )
        return True
    except Exception:
        return False

# ══════════════════════════════════════════════════════════════════════════════
#  FILE SCANNER
# ══════════════════════════════════════════════════════════════════════════════

_SCAN_DIRS = [
    os.environ.get("TEMP", ""),
    os.environ.get("TMP", ""),
    os.path.join(os.environ.get("USERPROFILE", ""), "AppData", "Roaming"),
    os.path.join(os.environ.get("USERPROFILE", ""), "AppData", "Local", "Temp"),
    r"C:\Users\Public",
    r"C:\Windows\Temp",
]

def scan_files() -> list[dict]:
    results = []
    for directory in _SCAN_DIRS:
        if not directory or not os.path.isdir(directory):
            continue
        try:
            for fname in os.listdir(directory):
                if not fname.lower().endswith((".exe", ".py", ".pyw", ".bat", ".vbs", ".ps1")):
                    continue
                fpath = os.path.join(directory, fname)
                reasons = _score(fname, fpath)
                if fname.lower().endswith(".exe"):
                    sig = _scan_binary(fpath)
                    if sig and sig not in reasons:
                        reasons.append(sig)
                if not reasons:
                    reasons.append("executable in drop zone")
                results.append({"name": fname, "path": fpath, "reasons": reasons})
        except PermissionError:
            pass
    return results

def delete_file(path: str) -> bool:
    try:
        os.remove(path)
        return True
    except Exception:
        return False

# ══════════════════════════════════════════════════════════════════════════════
#  CTk GUI
# ══════════════════════════════════════════════════════════════════════════════

ctk.set_appearance_mode("dark")

colors = {
    "white"     : "#ffffff",
    "red"       : "#a80505",
    "dark_red"  : "#800000",
    "dark_gray" : "#1e1e1e",
    "gray"      : "#444444",
    "light_gray": "#949494",
    "background": "#262626",
    "tab_bg"    : "#2e2e2e",
}

try:
    _is_admin = ctypes.windll.shell32.IsUserAnAdmin()
except Exception:
    _is_admin = False

root = ctk.CTk()
root.title(f"{name_tool} {version_tool} - Virus Remover")
root.geometry("980x720")
root.resizable(False, False)
root.configure(fg_color=colors["background"])
try:
    root.iconbitmap(os.path.join(tool_path, "Img", "RedTiger_icon.ico"))
except Exception: pass

# ── Header ─────────────────────────────────────────────────────────────────────
hdr = ctk.CTkFrame(root, height=70, fg_color=colors["dark_gray"], corner_radius=0)
hdr.pack(fill="x", side="top")
hdr.pack_propagate(False)

ctk.CTkLabel(hdr, text=name_tool,
             font=ctk.CTkFont(family="Helvetica", size=24, weight="bold"),
             text_color=colors["red"]).pack(side="left", padx=(20, 6), pady=15)
ctk.CTkLabel(hdr, text=f"{version_tool}  ·  Virus Remover",
             font=ctk.CTkFont(family="Helvetica", size=14),
             text_color=colors["light_gray"]).pack(side="left", pady=15)

if not _is_admin:
    ctk.CTkLabel(hdr,
                 text="⚠  Not running as Administrator — HKLM writes may fail",
                 font=ctk.CTkFont(size=11),
                 text_color="#ffaa00").pack(side="right", padx=20)

# ── Status bar ────────────────────────────────────────────────────────────────
status_var = ctk.StringVar(value="Ready  ·  select a scan tab and click Scan")
_sbar = ctk.CTkFrame(root, height=28, fg_color=colors["dark_gray"], corner_radius=0)
_sbar.pack(fill="x", side="bottom")
_sbar.pack_propagate(False)
ctk.CTkLabel(_sbar, textvariable=status_var,
             font=ctk.CTkFont(size=11), text_color=colors["light_gray"],
             anchor="w").pack(side="left", padx=12)

def _set_status(msg: str):
    root.after(0, lambda: status_var.set(msg))

# ── Tab view ──────────────────────────────────────────────────────────────────
tabs = ctk.CTkTabview(
    root,
    fg_color=colors["dark_gray"],
    segmented_button_fg_color=colors["dark_gray"],
    segmented_button_selected_color=colors["red"],
    segmented_button_selected_hover_color=colors["dark_red"],
    segmented_button_unselected_color=colors["dark_gray"],
    segmented_button_unselected_hover_color=colors["gray"],
    text_color="white",
    text_color_disabled=colors["light_gray"],
)
tabs.pack(fill="both", expand=True, padx=10, pady=(8, 6))

for _t in ("Registry", "Processes", "Files", "Full Scan"):
    tabs.add(_t)

# ── Shared helpers ─────────────────────────────────────────────────────────────
def _clear_frame(frame):
    for w in frame.winfo_children():
        w.destroy()

def _make_row(parent, item: dict, idx: int, action_cb=None, action_label="Delete"):
    reasons = item.get("reasons", [])
    is_sus  = bool(reasons)
    bg = colors["dark_gray"] if idx % 2 == 0 else "#202020"

    row = ctk.CTkFrame(parent, fg_color=bg, corner_radius=4)
    row.pack(fill="x", padx=4, pady=2)

    badge_bg  = colors["dark_red"] if is_sus else "#1a4d2e"
    badge_txt = "⚠ THREAT" if is_sus else "✓ CLEAN"
    ctk.CTkLabel(row, text=badge_txt, fg_color=badge_bg, corner_radius=4,
                 font=ctk.CTkFont(size=10, weight="bold"),
                 width=80, height=22, text_color="white").pack(side="left", padx=(8, 6), pady=8)

    info = ctk.CTkFrame(row, fg_color="transparent")
    info.pack(side="left", fill="x", expand=True, pady=4)

    name  = item.get("name", "?")
    extra = ""
    if "pid"  in item: extra = f"   PID {item['pid']}"
    if "hive" in item: extra = f"   [{item['hive']}\\…\\Run]"

    ctk.CTkLabel(info, text=name[:52] + extra,
                 font=ctk.CTkFont(size=12, weight="bold"),
                 text_color="white", anchor="w").pack(fill="x")

    path = item.get("path", "")
    if path and path.lower() != name.lower():
        ctk.CTkLabel(info, text=path[:78],
                     font=ctk.CTkFont(size=10), text_color="#777777", anchor="w").pack(fill="x")

    if reasons:
        ctk.CTkLabel(info, text=" · ".join(reasons)[:95],
                     font=ctk.CTkFont(size=10), text_color="#ffcc44", anchor="w").pack(fill="x")

    if is_sus and action_cb:
        ctk.CTkButton(row, text=action_label, width=68, height=26,
                      command=lambda i=item: action_cb(i),
                      fg_color=colors["dark_red"], hover_color=colors["red"],
                      font=ctk.CTkFont(size=11)).pack(side="right", padx=8)

def _tab_skeleton(tab_frame):
    tab_frame.grid_rowconfigure(1, weight=1)
    tab_frame.grid_columnconfigure(0, weight=1)
    top    = ctk.CTkFrame(tab_frame, height=46, fg_color=colors["background"])
    top.grid(row=0, column=0, sticky="ew", pady=(4, 2))
    scroll = ctk.CTkScrollableFrame(tab_frame, fg_color=colors["background"])
    scroll.grid(row=1, column=0, sticky="nsew")
    bottom = ctk.CTkFrame(tab_frame, height=44, fg_color=colors["background"])
    bottom.grid(row=2, column=0, sticky="ew", pady=(2, 0))
    return top, scroll, bottom

# ══════════════════════════════════════════════════════════════════════════════
#  REGISTRY TAB
# ══════════════════════════════════════════════════════════════════════════════
_reg_top, _reg_scroll, _reg_bot = _tab_skeleton(tabs.tab("Registry"))
_reg_items: list[dict] = []

def _reg_del(item):
    if messagebox.askyesno("Confirm Delete",
                           f"Delete registry entry:\n\n'{item['name']}'\n\nThis is permanent."):
        ok = _delete_registry_value(item["hive"], item["key"], item["name"])
        if ok:
            _set_status(f"Deleted '{item['name']}' from registry.")
            _do_scan_registry()
        else:
            messagebox.showerror("Error", "Failed — try running as Administrator.")

def _reg_del_all():
    sus = [i for i in _reg_items if i.get("reasons")]
    if not sus: return
    if messagebox.askyesno("Confirm", f"Delete ALL {len(sus)} suspicious registry entries?"):
        for item in sus:
            _delete_registry_value(item["hive"], item["key"], item["name"])
        _set_status(f"Deleted {len(sus)} registry entries.")
        _do_scan_registry()

def _do_scan_registry():
    global _reg_items
    _set_status("Scanning registry startup keys…")
    _btn_reg_scan.configure(state="disabled")
    _clear_frame(_reg_scroll)

    def _worker():
        global _reg_items
        try:    _reg_items = scan_registry()
        except: _reg_items = []
        root.after(0, _reg_render)

    def _reg_render():
        sus   = [i for i in _reg_items if i["reasons"]]
        clean = [i for i in _reg_items if not i["reasons"]]
        for idx, item in enumerate(sus + clean):
            _make_row(_reg_scroll, item, idx, action_cb=_reg_del, action_label="Delete")
        if not _reg_items:
            ctk.CTkLabel(_reg_scroll, text="No startup entries found.",
                         text_color=colors["light_gray"],
                         font=ctk.CTkFont(size=12)).pack(pady=24)
        elif not sus:
            ctk.CTkLabel(_reg_scroll, text="✓  No suspicious startup entries.",
                         text_color="#2d7a4f",
                         font=ctk.CTkFont(size=12, weight="bold")).pack(pady=10)
        _set_status(f"Registry: {len(_reg_items)} entries  ·  {len(sus)} suspicious")
        _btn_reg_scan.configure(state="normal")
        _btn_reg_delall.configure(state="normal" if sus else "disabled")

    threading.Thread(target=_worker, daemon=True).start()

ctk.CTkLabel(_reg_top,
             text="Startup registry scan  ·  Run / RunOnce keys + binary signature check",
             font=ctk.CTkFont(size=12), text_color=colors["light_gray"]).pack(side="left", padx=10)
_btn_reg_scan = ctk.CTkButton(_reg_top, text="Scan Registry", width=130, height=32,
                               fg_color=colors["red"], hover_color=colors["dark_red"],
                               font=ctk.CTkFont(size=12, weight="bold"),
                               command=_do_scan_registry)
_btn_reg_scan.pack(side="right", padx=10)

_btn_reg_delall = ctk.CTkButton(_reg_bot, text="Delete All Suspicious", width=165, height=32,
                                 state="disabled",
                                 fg_color=colors["dark_red"], hover_color=colors["red"],
                                 font=ctk.CTkFont(size=12),
                                 command=_reg_del_all)
_btn_reg_delall.pack(side="right", padx=10)

# ══════════════════════════════════════════════════════════════════════════════
#  PROCESSES TAB
# ══════════════════════════════════════════════════════════════════════════════
_proc_top, _proc_scroll, _proc_bot = _tab_skeleton(tabs.tab("Processes"))
_proc_items: list[dict] = []

def _proc_kill(item):
    if messagebox.askyesno("Confirm Kill",
                           f"Kill process:\n\n'{item['name']}'  PID {item['pid']}\n\nThis will terminate it immediately."):
        ok = kill_process(item["pid"], item["name"])
        if ok:
            _set_status(f"Killed '{item['name']}' PID {item['pid']}")
            _do_scan_procs()
        else:
            messagebox.showerror("Error", "Failed to kill process.")

def _proc_kill_all():
    sus = [i for i in _proc_items if i.get("reasons")]
    if not sus: return
    if messagebox.askyesno("Confirm", f"Kill ALL {len(sus)} suspicious processes?"):
        for item in sus:
            kill_process(item["pid"], item["name"])
        _set_status(f"Killed {len(sus)} processes.")
        _do_scan_procs()

def _do_scan_procs():
    global _proc_items
    _set_status("Scanning running processes…")
    _btn_proc_scan.configure(state="disabled")
    _clear_frame(_proc_scroll)

    def _worker():
        global _proc_items
        try:    _proc_items = scan_processes()
        except: _proc_items = []
        root.after(0, _proc_render)

    def _proc_render():
        sus     = [i for i in _proc_items if i["reasons"]]
        display = sus if sus else _proc_items[:200]
        for idx, item in enumerate(display):
            _make_row(_proc_scroll, item, idx, action_cb=_proc_kill, action_label="Kill")
        if not sus:
            ctk.CTkLabel(_proc_scroll, text="✓  No suspicious processes detected.",
                         text_color="#2d7a4f",
                         font=ctk.CTkFont(size=12, weight="bold")).pack(pady=24)
        _set_status(f"Processes: {len(_proc_items)} total  ·  {len(sus)} suspicious")
        _btn_proc_scan.configure(state="normal")
        _btn_proc_killall.configure(state="normal" if sus else "disabled")

    threading.Thread(target=_worker, daemon=True).start()

ctk.CTkLabel(_proc_top, text="Running process scan  ·  suspicious entries shown first",
             font=ctk.CTkFont(size=12), text_color=colors["light_gray"]).pack(side="left", padx=10)
_btn_proc_scan = ctk.CTkButton(_proc_top, text="Scan Processes", width=130, height=32,
                                fg_color=colors["red"], hover_color=colors["dark_red"],
                                font=ctk.CTkFont(size=12, weight="bold"),
                                command=_do_scan_procs)
_btn_proc_scan.pack(side="right", padx=10)

_btn_proc_killall = ctk.CTkButton(_proc_bot, text="Kill All Suspicious", width=155, height=32,
                                   state="disabled",
                                   fg_color=colors["dark_red"], hover_color=colors["red"],
                                   font=ctk.CTkFont(size=12),
                                   command=_proc_kill_all)
_btn_proc_killall.pack(side="right", padx=10)

# ══════════════════════════════════════════════════════════════════════════════
#  FILES TAB
# ══════════════════════════════════════════════════════════════════════════════
_file_top, _file_scroll, _file_bot = _tab_skeleton(tabs.tab("Files"))
_file_items: list[dict] = []

def _file_del(item):
    if messagebox.askyesno("Confirm Delete",
                           f"Delete file:\n\n{item['path']}\n\nThis is permanent."):
        ok = delete_file(item["path"])
        if ok:
            _set_status(f"Deleted '{item['name']}'")
            _do_scan_files()
        else:
            messagebox.showerror("Error", "Failed — file may be in use or locked.")

def _file_del_all():
    if not _file_items: return
    if messagebox.askyesno("Confirm", f"Delete ALL {len(_file_items)} suspicious files?\nThis is permanent."):
        for item in _file_items:
            delete_file(item["path"])
        _set_status(f"Deleted {len(_file_items)} files.")
        _do_scan_files()

def _do_scan_files():
    global _file_items
    _set_status("Scanning drop zones…")
    _btn_file_scan.configure(state="disabled")
    _clear_frame(_file_scroll)

    def _worker():
        global _file_items
        try:    _file_items = scan_files()
        except: _file_items = []
        root.after(0, _file_render)

    def _file_render():
        for idx, item in enumerate(_file_items):
            _make_row(_file_scroll, item, idx, action_cb=_file_del, action_label="Delete")
        if not _file_items:
            ctk.CTkLabel(_file_scroll, text="✓  No suspicious files found in drop zones.",
                         text_color="#2d7a4f",
                         font=ctk.CTkFont(size=12, weight="bold")).pack(pady=24)
        _set_status(f"Files: {len(_file_items)} suspicious file(s) in drop zones")
        _btn_file_scan.configure(state="normal")
        _btn_file_delall.configure(state="normal" if _file_items else "disabled")

    threading.Thread(target=_worker, daemon=True).start()

ctk.CTkLabel(_file_top, text="File drop zone scan  ·  %TEMP%, AppData, Public  +  binary signatures",
             font=ctk.CTkFont(size=12), text_color=colors["light_gray"]).pack(side="left", padx=10)
_btn_file_scan = ctk.CTkButton(_file_top, text="Scan Files", width=130, height=32,
                                fg_color=colors["red"], hover_color=colors["dark_red"],
                                font=ctk.CTkFont(size=12, weight="bold"),
                                command=_do_scan_files)
_btn_file_scan.pack(side="right", padx=10)

_btn_file_delall = ctk.CTkButton(_file_bot, text="Delete All Suspicious", width=165, height=32,
                                  state="disabled",
                                  fg_color=colors["dark_red"], hover_color=colors["red"],
                                  font=ctk.CTkFont(size=12),
                                  command=_file_del_all)
_btn_file_delall.pack(side="right", padx=10)

# ══════════════════════════════════════════════════════════════════════════════
#  FULL SCAN TAB
# ══════════════════════════════════════════════════════════════════════════════
_full_top, _full_scroll, _full_bot = _tab_skeleton(tabs.tab("Full Scan"))
_full_reg_sus:  list[dict] = []
_full_proc_sus: list[dict] = []
_full_file_sus: list[dict] = []

def _full_reg_del(item):
    if messagebox.askyesno("Confirm", f"Delete registry entry '{item['name']}'?"):
        _delete_registry_value(item["hive"], item["key"], item["name"])
        _set_status(f"Deleted '{item['name']}'")
        _do_full_scan()

def _full_proc_kill(item):
    if messagebox.askyesno("Confirm", f"Kill '{item['name']}' PID {item['pid']}?"):
        kill_process(item["pid"], item["name"])
        _set_status(f"Killed '{item['name']}'")
        _do_full_scan()

def _full_file_del(item):
    if messagebox.askyesno("Confirm", f"Delete '{item['path']}'?"):
        delete_file(item["path"])
        _set_status(f"Deleted '{item['name']}'")
        _do_full_scan()

def _full_clean_all():
    total = len(_full_reg_sus) + len(_full_proc_sus) + len(_full_file_sus)
    if total == 0: return
    if not messagebox.askyesno("Confirm Clean All", f"Remove ALL {total} threats?\nThis is permanent."):
        return
    for e in _full_reg_sus:
        _delete_registry_value(e["hive"], e["key"], e["name"])
    for p in _full_proc_sus:
        kill_process(p["pid"], p["name"])
    for f in _full_file_sus:
        delete_file(f["path"])
    _set_status(f"Cleaned {total} threats.")
    _do_full_scan()

def _do_full_scan():
    global _full_reg_sus, _full_proc_sus, _full_file_sus
    _set_status("Running full scan…")
    _btn_full_scan.configure(state="disabled")
    _clear_frame(_full_scroll)

    def _worker():
        global _full_reg_sus, _full_proc_sus, _full_file_sus
        try:    reg   = scan_registry()
        except: reg   = []
        try:    procs = scan_processes()
        except: procs = []
        try:    files = scan_files()
        except: files = []
        _full_reg_sus  = [e for e in reg   if e["reasons"]]
        _full_proc_sus = [p for p in procs if p["reasons"]]
        _full_file_sus = list(files)
        root.after(0, lambda: _full_render(reg, procs, files))

    def _full_render(reg, procs, files):
        sus_r = [e for e in reg   if e["reasons"]]
        sus_p = [p for p in procs if p["reasons"]]
        total = len(sus_r) + len(sus_p) + len(files)

        # Summary card
        card = ctk.CTkFrame(_full_scroll, fg_color=colors["dark_gray"], corner_radius=6)
        card.pack(fill="x", padx=4, pady=(4, 10))
        c_r = colors["red"] if sus_r else "#2d7a4f"
        c_p = colors["red"] if sus_p else "#2d7a4f"
        c_f = colors["red"] if files  else "#2d7a4f"
        ctk.CTkLabel(card, text=f"Registry   : {len(sus_r)} suspicious / {len(reg)} entries",
                     text_color=c_r, font=ctk.CTkFont(size=12), anchor="w").pack(fill="x", padx=14, pady=(8,2))
        ctk.CTkLabel(card, text=f"Processes  : {len(sus_p)} suspicious / {len(procs)} total",
                     text_color=c_p, font=ctk.CTkFont(size=12), anchor="w").pack(fill="x", padx=14, pady=2)
        ctk.CTkLabel(card, text=f"Files      : {len(files)} found in drop zones",
                     text_color=c_f, font=ctk.CTkFont(size=12), anchor="w").pack(fill="x", padx=14, pady=(2,8))

        idx = 0
        if sus_r:
            ctk.CTkLabel(_full_scroll, text="  Registry — Startup Keys",
                         font=ctk.CTkFont(size=11, weight="bold"),
                         text_color=colors["red"]).pack(anchor="w", padx=8, pady=(2,0))
            for item in sus_r:
                _make_row(_full_scroll, item, idx, action_cb=_full_reg_del, action_label="Delete")
                idx += 1

        if sus_p:
            ctk.CTkLabel(_full_scroll, text="  Processes — Running",
                         font=ctk.CTkFont(size=11, weight="bold"),
                         text_color=colors["red"]).pack(anchor="w", padx=8, pady=(6,0))
            for item in sus_p:
                _make_row(_full_scroll, item, idx, action_cb=_full_proc_kill, action_label="Kill")
                idx += 1

        if files:
            ctk.CTkLabel(_full_scroll, text="  Files — Drop Zones",
                         font=ctk.CTkFont(size=11, weight="bold"),
                         text_color=colors["red"]).pack(anchor="w", padx=8, pady=(6,0))
            for item in files:
                _make_row(_full_scroll, item, idx, action_cb=_full_file_del, action_label="Delete")
                idx += 1

        if total == 0:
            ctk.CTkLabel(_full_scroll, text="✓  System looks clean.",
                         text_color="#2d7a4f",
                         font=ctk.CTkFont(size=14, weight="bold")).pack(pady=36)

        _set_status(f"Full scan complete  ·  {total} threat(s) found")
        _btn_full_scan.configure(state="normal")
        _btn_full_clean.configure(state="normal" if total > 0 else "disabled")

    threading.Thread(target=_worker, daemon=True).start()

ctk.CTkLabel(_full_top, text="Full scan  ·  Registry + Processes + Drop Zones",
             font=ctk.CTkFont(size=12), text_color=colors["light_gray"]).pack(side="left", padx=10)
_btn_full_scan = ctk.CTkButton(_full_top, text="Run Full Scan", width=130, height=32,
                                fg_color=colors["red"], hover_color=colors["dark_red"],
                                font=ctk.CTkFont(size=12, weight="bold"),
                                command=_do_full_scan)
_btn_full_scan.pack(side="right", padx=10)

_btn_full_clean = ctk.CTkButton(_full_bot, text="Clean All Threats", width=155, height=32,
                                 state="disabled",
                                 fg_color=colors["dark_red"], hover_color=colors["red"],
                                 font=ctk.CTkFont(size=12),
                                 command=_full_clean_all)
_btn_full_clean.pack(side="right", padx=10)

# ══════════════════════════════════════════════════════════════════════════════
root.mainloop()
